// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxlmjzqsfgghdukqixx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeGxtanpxc2ZnZ2hkdWtxaXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzYzNTUsImV4cCI6MjA1NDg1MjM1NX0.WucKVDf09FzdgycfJ1V1gntEvh_vMYEXzD-Msq0mk0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);